include_guard(GLOBAL)
find_package(libuv CONFIG REQUIRED)
add_library(libnet_uv STATIC "${CMAKE_CURRENT_LIST_DIR}/../src/libnet_uv.cc")
add_library(devkit::libnet_uv ALIAS libnet_uv)
target_compile_features(libnet_uv PUBLIC cxx_std_20)
set_target_properties(libnet_uv PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(libnet_uv PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/../include>")
if(TARGET libuv::uv_a)
  target_link_libraries(libnet_uv PUBLIC libuv::uv_a)
else()
  target_link_libraries(libnet_uv PUBLIC libuv::uv)
endif()
install(TARGETS libnet_uv ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}")
install(FILES "${CMAKE_CURRENT_LIST_DIR}/../include/libnet_uv.h" DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
