#ifndef __TESTS_TEST_SK_STDAFX_H_
#define __TESTS_TEST_SK_STDAFX_H_
#include <iostream>
#include <sk.h>
#include <stl.h>
#include <string.h>
#include <fmt/format.h>
#include "tests.h"
#include "fps.h"
#endif ///__TESTS_TEST_SK_STDAFX_H_