include(CTest)
include(GNUInstallDirs)
include(CMakePackageConfigHelpers)
find_package(Threads REQUIRED)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
if(WIN32)
  set(ble_backend src/windows/backend.cpp)
elseif(ANDROID)
  set(ble_backend src/android/backend.cpp)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(GIO REQUIRED IMPORTED_TARGET gio-2.0 gio-unix-2.0)
  set(ble_backend src/linux/backend.cpp)
else()
  message(FATAL_ERROR "libble has no backend for ${CMAKE_SYSTEM_NAME}")
endif()
add_library(devkit_ble SHARED src/common/abi.cpp ${ble_backend} src/version.c)
add_library(devkit::ble ALIAS devkit_ble)
target_compile_features(devkit_ble PRIVATE cxx_std_20)
target_compile_definitions(devkit_ble PRIVATE DEVKIT_BLE_BUILD=1 "DKBLE_VERSION=\"${NATIVE_LIBS_VERSION}\"")
target_include_directories(devkit_ble PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:include>)
target_link_libraries(devkit_ble PRIVATE Threads::Threads)
set_target_properties(devkit_ble PROPERTIES EXPORT_NAME ble OUTPUT_NAME devkit_ble VERSION ${NATIVE_LIBS_VERSION} SOVERSION 1
  C_VISIBILITY_PRESET hidden CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN ON)
if(WIN32)
  target_compile_definitions(devkit_ble PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
  target_link_libraries(devkit_ble PRIVATE windowsapp ole32 runtimeobject)
  target_compile_options(devkit_ble PRIVATE /W4 /utf-8)
elseif(ANDROID)
  target_link_libraries(devkit_ble PRIVATE log)
  target_link_options(devkit_ble PRIVATE "LINKER:--exclude-libs,ALL")
else()
  target_link_libraries(devkit_ble PRIVATE PkgConfig::GIO)
  target_compile_options(devkit_ble PRIVATE -Wall -Wextra -Wpedantic)
endif()
if(UNIX)
  target_link_options(devkit_ble PRIVATE "LINKER:--version-script,${CMAKE_CURRENT_SOURCE_DIR}/src/common/exports.map")
  set_property(TARGET devkit_ble APPEND PROPERTY LINK_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/common/exports.map")
endif()
install(TARGETS devkit_ble EXPORT devkitBleTargets LIBRARY DESTINATION lib RUNTIME DESTINATION bin ARCHIVE DESTINATION lib)
install(FILES include/libble/ble.h DESTINATION include/libble)
install(FILES LICENSE README.md DESTINATION share/libble)
install(DIRECTORY docs/ DESTINATION share/libble/docs)
install(DIRECTORY examples/consumer DESTINATION share/libble/examples)
if(ANDROID)
  install(DIRECTORY android/ DESTINATION share/libble/android)
endif()
install(EXPORT devkitBleTargets NAMESPACE devkit:: DESTINATION lib/cmake/devkitBle)
configure_package_config_file(cmake/devkitBleConfig.cmake.in "${CMAKE_CURRENT_BINARY_DIR}/devkitBleConfig.cmake" INSTALL_DESTINATION lib/cmake/devkitBle)
write_basic_package_version_file("${CMAKE_CURRENT_BINARY_DIR}/devkitBleConfigVersion.cmake" VERSION ${NATIVE_LIBS_VERSION} COMPATIBILITY SameMinorVersion)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/devkitBleConfig.cmake" "${CMAKE_CURRENT_BINARY_DIR}/devkitBleConfigVersion.cmake" cmake/BundleRuntime.cmake DESTINATION lib/cmake/devkitBle)
if(BUILD_TESTING)
  add_executable(ble_portable_state_test src/common/abi.cpp src/version.c tests/portable_state.cpp)
  target_compile_features(ble_portable_state_test PRIVATE cxx_std_20)
  target_include_directories(ble_portable_state_test PRIVATE include)
  target_compile_definitions(ble_portable_state_test PRIVATE DEVKIT_BLE_BUILD=1 "DKBLE_VERSION=\"${NATIVE_LIBS_VERSION}\"")
  target_link_libraries(ble_portable_state_test PRIVATE Threads::Threads)
  add_test(NAME libble.portable_state COMMAND ble_portable_state_test)
  set_tests_properties(libble.portable_state PROPERTIES TIMEOUT 20)
endif()

option(LIBBLE_RADIO_FIXTURE "Build explicitly invoked synthetic radio interoperability fixture" OFF)
if(LIBBLE_RADIO_FIXTURE AND NOT ANDROID)
  add_executable(ble_radio_fixture tests/radio_fixture.cpp)
  target_compile_features(ble_radio_fixture PRIVATE cxx_std_20)
  target_link_libraries(ble_radio_fixture PRIVATE devkit_ble)
  include(cmake/BundleRuntime.cmake)
  devkit_ble_bundle(ble_radio_fixture)
endif()
