
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/k34ub/Downloads/cmake-3.28.0-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/k34ub/Downloads/cmake-3.28.0-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/k34ub/Downloads/cmake-3.28.0-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/k34ub/Downloads/cmake-3.28.0-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 2024/6/16 13:38:45.
      Project "C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\3.28.0\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\3.28.0\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\3.28.0\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.96
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/k34ub/source/skstu/devkit/projects/win32vs/3rdparty/dlfcn-win32/CMakeFiles/3.28.0/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/k34ub/Downloads/cmake-3.28.0-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/k34ub/Downloads/cmake-3.28.0-windows-x86_64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/k34ub/source/skstu/devkit/projects/win32vs/3rdparty/dlfcn-win32/CMakeFiles/CMakeScratch/TryCompile-53tzoh"
      binary: "C:/Users/k34ub/source/skstu/devkit/projects/win32vs/3rdparty/dlfcn-win32/CMakeFiles/CMakeScratch/TryCompile-53tzoh"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/k34ub/source/skstu/devkit/projects/win32vs/3rdparty/dlfcn-win32/CMakeFiles/CMakeScratch/TryCompile-53tzoh'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_23ede.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
        Copyright (C) Microsoft Corporation. All rights reserved.
        
        Build started 2024/6/16 13:38:47.
        Project "C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\CMakeScratch\\TryCompile-53tzoh\\cmTC_23ede.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_23ede.dir\\Debug\\".
          Creating directory "C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\CMakeScratch\\TryCompile-53tzoh\\Debug\\".
          Creating directory "cmTC_23ede.dir\\Debug\\cmTC_23ede.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_23ede.dir\\Debug\\cmTC_23ede.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_23ede.dir\\Debug\\\\" /Fd"cmTC_23ede.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\k34ub\\Downloads\\cmake-3.28.0-windows-x86_64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_23ede.dir\\Debug\\\\" /Fd"cmTC_23ede.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\k34ub\\Downloads\\cmake-3.28.0-windows-x86_64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\CMakeScratch\\TryCompile-53tzoh\\Debug\\cmTC_23ede.exe" /INCREMENTAL /ILK:"cmTC_23ede.dir\\Debug\\cmTC_23ede.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/k34ub/source/skstu/devkit/projects/win32vs/3rdparty/dlfcn-win32/CMakeFiles/CMakeScratch/TryCompile-53tzoh/Debug/cmTC_23ede.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/k34ub/source/skstu/devkit/projects/win32vs/3rdparty/dlfcn-win32/CMakeFiles/CMakeScratch/TryCompile-53tzoh/Debug/cmTC_23ede.lib" /MACHINE:X64  /machine:x64 cmTC_23ede.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_23ede.vcxproj -> C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\CMakeScratch\\TryCompile-53tzoh\\Debug\\cmTC_23ede.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_23ede.dir\\Debug\\cmTC_23ede.tlog\\unsuccessfulbuild".
          Touching "cmTC_23ede.dir\\Debug\\cmTC_23ede.tlog\\cmTC_23ede.lastbuildstate".
        Done Building Project "C:\\Users\\k34ub\\source\\skstu\\devkit\\projects\\win32vs\\3rdparty\\dlfcn-win32\\CMakeFiles\\CMakeScratch\\TryCompile-53tzoh\\cmTC_23ede.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.84
        
      exitCode: 0
...
