name: devkit_flui_renderer
publish_to: none
version: 0.1.1
environment:
  sdk: '>=3.13.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.3
  ffi: 2.2.0
  xml: 6.6.1
  collection: 1.19.1
  flutter_svg: 2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
